description: Simple Amulet job on Singularity

target:
  service: sing
  name: msroctobasicvc
  workspace_name: dca-singularity

environment:
  image: amlt-sing/acpt-rocm6.1_ubuntu20.04_py3.9_pytorch2.1.2
  setup:
    - pwd
    - sudo apt-get update
    - sudo apt-get install -y vim
    - pip install uv
    - uv venv venv_bd --python 3.11
    - source venv_bd/bin/activate
    - ls -l
    - uv pip install --upgrade pip setuptools packaging wheel ninja

    # bitsandbytes HIP bug
    # - line=major, minor = map(int, torch.version.cuda.split("."))
    # - pip install --force-reinstall 'https://github.com/bitsandbytes-foundation/bitsandbytes/releases/download/continuous-release_multi-backend-refactor/bitsandbytes-0.45.3.dev272-py3-none-manylinux_2_24_x86_64.whl'
    
    - uv pip install torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 --index-url https://download.pytorch.org/whl/rocm6.1
    - cd /scratch/amlt_code
    - uv pip install -r ./requirement_20250507_transformers_4.51.3.txt
    - uv pip install flash-attn==2.7.4.post1 --no-build-isolation

    - echo -e "alias ll='ls -al'" >> ~/.bashrc

storage:
  input:
    storage_account_name: dcasingularity4556773921
    container_name: qingtaoli
    mount_dir: /mnt/input
  output:
    storage_account_name: dcasingularity4556773921
    container_name: qingtaoli
    mount_dir: /mnt/output
  external:
    storage_account_name: dcasingularity4556773921
    container_name: qingtaoli
    mount_dir: /mnt/external

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: ./

data:
  storage_id: external


jobs:
- name: mi300_test
  sku: NDMI300Xv5:G8
  identity: managed
  submit_args:
    env:
      _AZUREML_SINGULARITY_JOB_UAI: "/subscriptions/656a79af-6a27-4924-ad92-9221860e3bba/resourceGroups/dca-core/providers/Microsoft.ManagedIdentity/userAssignedIdentities/dca-core-identity"
  command:
    - cd train
    - chmod +x ./train*.sh
    - export NCCL_DEBUG=WARN
    # - ./train.sh /mnt/external/models/deepseek-ai/DeepSeek-R1-Distill-Qwen-14B/ /mnt/external/checkpoints/DeepSeek-R1-Distill-Qwen-14B/alpaca5kwiki3k_ctx4096/ /mnt/external/data/generation/DeepSeek-R1-Distill-Qwen-14B-ctx4096/wiki-alpaca/mix_alpaca_wikitext_8000.json /mnt/external/checkpoints/DeepSeek-R1-Distill-Qwen-14B/alpaca5kwiki3k_ctx4096/logs/ /mnt/external/data/clip_cache/deepseek-ai/DeepSeek-R1-Distill-Qwen-14B/int2-g64.pt 4096
    - ./train_8gpu_7b.sh /mnt/external/models/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B/ /mnt/external/checkpoints/DeepSeek-R1-Distill-Qwen-7B/openr1_math220k_default_ctx4096/ /mnt/external/data/OpenR1-Math-220k/default.json /mnt/external/checkpoints/DeepSeek-R1-Distill-Qwen-7B/openr1_math220k_default_ctx4096/logs/ /mnt/external/data/clip_cache/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B/int2-g64.pt 4096
    - cd /mnt/external
    - nohup python keep.py --gpus=8 >/dev/null 2>&1 &
    - sleep 1000000
  tags: ["Debug:True"]
  priority: High
  azml_int: True
