description: Simple Amulet job on Singularity

target:
  service: sing
  name: msrresrchbasicvc
  workspace_name: dca-singularity

environment:
  image: amlt-sing/acpt-torch2.6.0-py3.10-cuda12.6-ubuntu22.04
  setup:
    - pwd
    - sudo apt-get update
    - sudo apt-get install -y vim
    - pip install uv
    - uv venv venv_bd --python 3.11
    - source venv_bd/bin/activate
    - ls -l
    - uv pip install --upgrade pip setuptools packaging wheel ninja

    - uv pip install torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1
    - cd /scratch/amlt_code
    - uv pip install -r ./requirement_20250507_transformers_4.51.3.txt
    - uv pip install flash-attn==2.7.4.post1 --no-build-isolation
    - DS_BUILD_CPU_ADAM=1 DS_BUILD_FUSED_ADAM=1 DS_BUILD_TRANSFORMER=1 pip install deepspeed==0.15.4

    - echo -e "alias ll='ls -al'" >> ~/.bashrc

    - cd /scratch/amlt_code/scripts/code_modify
    - chmod +x ./modify*.sh
    - ./modify_for_bd_train.sh

storage:
  input:
    storage_account_name: dcasingularity4556773921
    container_name: qingtaoli
    mount_dir: /mnt/input
  output:
    storage_account_name: dcasingularity4556773921
    container_name: qingtaoli
    mount_dir: /mnt/output
  external:
    storage_account_name: dcasingularity4556773921
    container_name: qingtaoli
    mount_dir: /mnt/external

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: ./

data:
  storage_id: external


jobs:
- name: bd_train_4xA100-NvLink_qwen3_14b_V1_nemotron_code_cakld_ctx16384_test
  # sku: NC_A100_v4:G8
  # sku: 1x80G8-A100-IB-NvLink
  # sku: 1x80G4-A100-NvLink
  sku: 1x80G16-A100-NvLink
  identity: managed
  submit_args:
    env:
      _AZUREML_SINGULARITY_JOB_UAI: "/subscriptions/656a79af-6a27-4924-ad92-9221860e3bba/resourceGroups/dca-core/providers/Microsoft.ManagedIdentity/userAssignedIdentities/dca-core-identity"
  command:
    - cd scripts/train
    - chmod +x ./train*.sh
    - export NCCL_DEBUG=INFO

    ### V1.0 summary
    # - ./train_cosine_zero3.sh Qwen/Qwen3-14B /mnt/external/checkpoints/Qwen/Qwen3-14B/nemotron_code_cakld_ctx32768/ /mnt/external/data/nemotron/code/nemotron-sft-code_500K_block_0.jsonl /mnt/external/checkpoints/Qwen/Qwen3-14B/nemotron_code_cakld_ctx32768/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-14B/int2-g64-code_nemotron.pt 32768
    - ./train_cosine_zero3.sh Qwen/Qwen3-14B /mnt/external/checkpoints/Qwen/Qwen3-14B/nemotron_code_cakld_ctx16384_test/ /mnt/external/data/nemotron/code/nemotron-sft-code_500K_block_0.jsonl /mnt/external/checkpoints/Qwen/Qwen3-14B/nemotron_code_cakld_ctx16384_test/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-14B/int2-g64-code_nemotron.pt 16384
    # - ./train_cosine.sh Qwen/Qwen3-14B /mnt/external/checkpoints/Qwen/Qwen3-14B/nemotron_code_cakld_ctx16384/ /mnt/external/data/nemotron/code/nemotron-sft-code_500K_block_0_repeat4.jsonl /mnt/external/checkpoints/Qwen/Qwen3-14B/nemotron_code_cakld_ctx16384/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-14B/int2-g64-code_nemotron.pt 16384

    - cd /mnt/external
    - nohup python keep.py --gpus=4 --interval=0.2 >/dev/null 2>&1 &
    - sleep 100000000

  tags: ["Debug:True"]
  priority: High
  azml_int: True
