description: Simple Amulet job on Singularity

target:
  service: sing
  name: whitney08
  workspace_name: dca-singularity

environment:
  image: amlt-sing/acpt-rocm6.1_ubuntu20.04_py3.9_pytorch2.1.2
  setup:
    - pwd
    - sudo apt-get update
    - sudo apt-get install -y openmpi-bin libopenmpi-dev
    - sudo apt-get upgrade -y
    - sudo apt-get install -y vim
    - pip install uv
    - uv venv venv_bd --python 3.11
    - source venv_bd/bin/activate
    - ls -l
    - uv pip install --upgrade pip setuptools packaging wheel ninja

    # bitsandbytes HIP bug
    # - line=major, minor = map(int, torch.version.cuda.split("."))
    # - pip install --force-reinstall 'https://github.com/bitsandbytes-foundation/bitsandbytes/releases/download/continuous-release_multi-backend-refactor/bitsandbytes-0.45.3.dev272-py3-none-manylinux_2_24_x86_64.whl'
    
    - uv pip install torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 --index-url https://download.pytorch.org/whl/rocm6.1
    - cd /scratch/amlt_code
    - uv pip install -r ./requirement_20250507_transformers_4.51.3.txt
    - uv pip install flash-attn==2.7.4.post1 --no-build-isolation
    - DS_BUILD_CPU_ADAM=1 DS_BUILD_FUSED_ADAM=1 DS_BUILD_TRANSFORMER=1 pip install deepspeed==0.15.4

    - echo -e "alias ll='ls -al'" >> ~/.bashrc

    - cd /scratch/amlt_code/scripts/code_modify
    - chmod +x ./modify*.sh
    - ./modify_for_bd_train.sh

storage:
  input:
    storage_account_name: dcasingularity4556773921
    container_name: qingtaoli
    mount_dir: /mnt/input
  output:
    storage_account_name: dcasingularity4556773921
    container_name: qingtaoli
    mount_dir: /mnt/output
  external:
    storage_account_name: dcasingularity4556773921
    container_name: qingtaoli
    mount_dir: /mnt/external

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: ./

data:
  storage_id: external


jobs:
- name: bd_MI300_qwen3_14b_V1_nemotron_code_cakld_ctx16384
  sku: 1x192G8-MI300X-IB-xGMI
  # sku: 1x192G4-MI300X
  identity: managed
  submit_args:
    env:
      _AZUREML_SINGULARITY_JOB_UAI: "/subscriptions/656a79af-6a27-4924-ad92-9221860e3bba/resourceGroups/dca-core/providers/Microsoft.ManagedIdentity/userAssignedIdentities/dca-core-identity"
  command:
    - cd scripts/train
    - chmod +x ./train*.sh
    - export NCCL_DEBUG=INFO
    # - export HSA_FORCE_FINE_GRAIN_PCIE=1
    # - export NCCL_MIN_NCHANNELS=24
    # - export RCCL_MSCCLPP_ENABLE=1
    # - export NCCL_COLLNET_ENABLE=0
    
    ### Old models training
    # - ./train_8gpu_14b.sh /mnt/external/models/deepseek-ai/DeepSeek-R1-Distill-Qwen-14B/ /mnt/external/checkpoints/DeepSeek-R1-Distill-Qwen-14B_teacher_gen/20250513_openr1_math220k_default_ctx32k/ /mnt/external/data/teacher_gen/Qwen-14B/default.json /mnt/external/checkpoints/DeepSeek-R1-Distill-Qwen-14B_teacher_gen/20250513_openr1_math220k_default_ctx32k/logs/ /mnt/external/data/clip_cache/deepseek-ai/DeepSeek-R1-Distill-Qwen-14B/int2-g64.pt 32768
    # - ./train.sh /mnt/external/models/microsoft/Phi-4-reasoning/ /mnt/external/checkpoints/microsoft/Phi-4-reasoning/20250525_alpaca5kwiki3k_ctx4096/ /mnt/external/data/generation/microsoft/Phi-4-reasoning-ctx4096/wiki-alpaca/mix_alpaca_wikitext_8000.json /mnt/external/checkpoints/microsoft/Phi-4-reasoning/20250525_alpaca5kwiki3k_ctx4096/logs/ /mnt/external/data/clip_cache/microsoft/Phi-4-reasoning/int2-g64.pt 4096
    # - ./train.sh Qwen/Qwen3-8B /mnt/external/checkpoints/Qwen/Qwen3-8B/1b-grad-l3-r0.5_cakld_ctx4096/ /mnt/external/data/data_efficacy/processed_1b-grad-l3-r0.5.jsonl /mnt/external/checkpoints/Qwen/Qwen3-8B/1b-grad-l3-r0.5_cakld_ctx4096/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-8B/int2-g64.pt 4096
    # - ./train.sh Qwen/Qwen3-8B /mnt/external/checkpoints/Qwen/Qwen3-8B/1b-random-r0.5_nokd_ctx4096/ /mnt/external/data/data_efficacy/processed_1b-random-r0.5.jsonl /mnt/external/checkpoints/Qwen/Qwen3-8B/1b-random-r0.5_nokd_ctx4096/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-8B/int2-g64.pt 4096
    # - ./train.sh Qwen/Qwen3-8B /mnt/external/checkpoints/Qwen/Qwen3-8B/1b-grad-l3-r0.5_nokd_ctx4096/ /mnt/external/data/data_efficacy/processed_1b-grad-l3-r0.5.jsonl /mnt/external/checkpoints/Qwen/Qwen3-8B/1b-grad-l3-r0.5_nokd_ctx4096/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-8B/int2-g64.pt 4096
    # - ./train.sh Qwen/Qwen3-8B /mnt/external/checkpoints/Qwen/Qwen3-8B/OpenR1-Math-220k_default_cakld_ctx4096/ /mnt/external/data/OpenR1-Math-220k/default.json /mnt/external/checkpoints/Qwen/Qwen3-8B/OpenR1-Math-220k_default_cakld_ctx4096_batch16/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-8B/int2-g64.pt 4096
    # - ./train.sh Qwen/Qwen3-8B /mnt/external/checkpoints/Qwen/Qwen3-8B/wikialpaca_cakld_ctx4096/ /mnt/external/data/generation/Qwen/Qwen3-8B-ctx4096/wiki-alpaca/mix_alpaca_wikitext_8000.json /mnt/external/checkpoints/Qwen/Qwen3-8B/wikialpaca_cakld_ctx4096/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-8B/int2-g64.pt 4096
    
    ### Qwen3-14B training
    # - ./train.sh Qwen/Qwen3-14B /mnt/external/checkpoints/Qwen/Qwen3-14B/1b-grad-l3-r0.5_cakld_ctx4096/ /mnt/external/data/data_efficacy/processed_1b-grad-l3-r0.5.jsonl /mnt/external/checkpoints/Qwen/Qwen3-14B/1b-grad-l3-r0.5_cakld_ctx4096/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-14B/int2-g64.pt 4096
    # - ./train.sh Qwen/Qwen3-14B /mnt/external/checkpoints/Qwen/Qwen3-14B/1b-random-r0.5_cakld_ctx4096/ /mnt/external/data/data_efficacy/processed_1b-random-r0.5.jsonl /mnt/external/checkpoints/Qwen/Qwen3-14B/1b-random-r0.5_cakld_ctx4096/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-14B/int2-g64.pt 4096
    # - ./train.sh Qwen/Qwen3-14B /mnt/external/checkpoints/Qwen/Qwen3-14B/1b-grad-l3-r0.5_nokd_ctx4096/ /mnt/external/data/data_efficacy/processed_1b-grad-l3-r0.5.jsonl /mnt/external/checkpoints/Qwen/Qwen3-14B/1b-grad-l3-r0.5_nokd_ctx4096/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-14B/int2-g64.pt 4096
    # - ./train.sh Qwen/Qwen3-14B /mnt/external/checkpoints/Qwen/Qwen3-14B/1b-random-r0.5_nokd_ctx4096/ /mnt/external/data/data_efficacy/processed_1b-random-r0.5.jsonl /mnt/external/checkpoints/Qwen/Qwen3-14B/1b-random-r0.5_nokd_ctx4096/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-14B/int2-g64.pt 4096
    # - ./train.sh Qwen/Qwen3-14B /mnt/external/checkpoints/Qwen/Qwen3-14B/OpenR1-Math-220k_default_cakld_ctx4096/ /mnt/external/data/OpenR1-Math-220k/default.json /mnt/external/checkpoints/Qwen/Qwen3-14B/OpenR1-Math-220k_default_cakld_ctx4096/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-14B/int2-g64.pt 4096
    # - ./train.sh Qwen/Qwen3-14B /mnt/external/checkpoints/Qwen/Qwen3-14B/wikialpaca_cakld_ctx4096/ /mnt/external/data/generation/Qwen/Qwen3-14B-ctx4096/wiki-alpaca/mix_alpaca_wikitext_8000.json /mnt/external/checkpoints/Qwen/Qwen3-14B/wikialpaca_cakld_ctx4096/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-14B/int2-g64.pt 4096
    # - ./train.sh Qwen/Qwen3-14B /mnt/external/checkpoints/Qwen/Qwen3-14B/epicoder-func-380k_cakld_ctx4096/ /mnt/external/data/EpiCoder-func-380k/epicoder-func-380k.jsonl /mnt/external/checkpoints/Qwen/Qwen3-14B/epicoder-func-380k_cakld_ctx4096/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-14B/int2-g64.pt 4096
    # - ./train.sh Qwen/Qwen3-14B /mnt/external/checkpoints/Qwen/Qwen3-14B/merged_gmc_90k_90k_90k_cakld_ctx4096/ /mnt/external/data/merged_dataset/merged_gmc_90k_90k_90k.jsonl /mnt/external/checkpoints/Qwen/Qwen3-14B/merged_gmc_90k_90k_90k_cakld_ctx4096/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-14B/int2-g64.pt 4096
    # - ./train.sh Qwen/Qwen3-14B /mnt/external/checkpoints/Qwen/Qwen3-14B/nemotron_code_char16k_cakld_ctx4096/ /mnt/external/data/nemotron/nemotron-sft-code-char16k_526k.jsonl /mnt/external/checkpoints/Qwen/Qwen3-14B/nemotron_code_char16k_cakld_ctx4096/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-14B/int2-g64.pt 4096
    # - ./train_batch1.sh Qwen/Qwen3-14B /mnt/external/checkpoints/Qwen/Qwen3-14B/nemotron_code_char64k_cakld_ctx16384/ /mnt/external/data/nemotron/nemotron-sft-code-char64k_644k.jsonl /mnt/external/checkpoints/Qwen/Qwen3-14B/nemotron_code_char64k_cakld_ctx16384/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-14B/int2-g64.pt 16384
    # - ./train.sh Qwen/Qwen3-14B /mnt/external/checkpoints/Qwen/Qwen3-14B/nemotron_math_char16k_cakld_ctx4096/ /mnt/external/data/nemotron/nemotron-sft-math-char16k_273k.jsonl /mnt/external/checkpoints/Qwen/Qwen3-14B/nemotron_math_char16k_cakld_ctx4096/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-14B/int2-g64.pt 4096
    # - ./train_batch1.sh Qwen/Qwen3-14B /mnt/external/checkpoints/Qwen/Qwen3-14B/nemotron_math_char64k_cakld_ctx16384/ /mnt/external/data/nemotron/nemotron-sft-math-char64k_500k.jsonl /mnt/external/checkpoints/Qwen/Qwen3-14B/nemotron_math_char64k_cakld_ctx16384/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-14B/int2-g64.pt 16384
    # - ./train.sh Qwen/Qwen3-14B /mnt/external/checkpoints/Qwen/Qwen3-14B/nemotron_code_char16k_cakld_ctx4096_epoch4/ /mnt/external/data/nemotron/nemotron-sft-code-char16k_76.8k_repeat4.jsonl /mnt/external/checkpoints/Qwen/Qwen3-14B/nemotron_code_char16k_cakld_ctx4096_epoch4/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-14B/int2-g64.pt 4096

    ### Learning rate
    # - ./train_warmup.sh Qwen/Qwen3-14B /mnt/external/checkpoints/Qwen/Qwen3-14B/merged_gmc_90k_90k_90k_cakld_ctx4096_warmup/ /mnt/external/data/merged_dataset/merged_gmc_90k_90k_90k.jsonl /mnt/external/checkpoints/Qwen/Qwen3-14B/merged_gmc_90k_90k_90k_cakld_ctx4096_warmup/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-14B/int2-g64.pt 4096
    # - ./train.sh Qwen/Qwen3-14B /mnt/external/checkpoints/Qwen/Qwen3-14B/merged_gmc_90k_90k_90k_cakld_ctx4096_lr1e-6/ /mnt/external/data/merged_dataset/merged_gmc_90k_90k_90k.jsonl /mnt/external/checkpoints/Qwen/Qwen3-14B/merged_gmc_90k_90k_90k_cakld_ctx4096_lr1e-6/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-14B/int2-g64.pt 4096
    # - ./train.sh Qwen/Qwen3-14B /mnt/external/checkpoints/Qwen/Qwen3-14B/OpenR1-Math-220k_default_cakld_ctx4096_lr1e-6/ /mnt/external/data/OpenR1-Math-220k/default.json /mnt/external/checkpoints/Qwen/Qwen3-14B/OpenR1-Math-220k_default_cakld_ctx4096_lr1e-6/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-14B/int2-g64.pt 4096
    # - ./train_cosine.sh Qwen/Qwen3-14B /mnt/external/checkpoints/Qwen/Qwen3-14B/merged_gmc_90k_90k_90k_cakld_ctx4096_cosine_cycle300/ /mnt/external/data/merged_dataset/merged_gmc_90k_90k_90k.jsonl /mnt/external/checkpoints/Qwen/Qwen3-14B/merged_gmc_90k_90k_90k_cakld_ctx4096_cosine_cycle300/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-14B/int2-g64.pt 4096

    ### Clipping
    # - ./train.sh Qwen/Qwen3-14B /mnt/external/checkpoints/Qwen/Qwen3-14B/merged_gmc_90k_90k_90k_cakld_ctx4096_self_clip/ /mnt/external/data/merged_dataset/merged_gmc_90k_90k_90k.jsonl /mnt/external/checkpoints/Qwen/Qwen3-14B/merged_gmc_90k_90k_90k_cakld_ctx4096_self_clip/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-14B/int2-g64-merged_gmc.pt 4096
    # - ./train.sh Qwen/Qwen3-14B /mnt/external/checkpoints/Qwen/Qwen3-14B/nemotron_math_char16k_cakld_ctx4096_self_clip/ /mnt/external/data/nemotron/nemotron-sft-math-char16k_273k.jsonl /mnt/external/checkpoints/Qwen/Qwen3-14B/nemotron_math_char16k_cakld_ctx4096_self_clip/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-14B/int2-g64-math_nemotron.pt 4096
    # - ./train.sh Qwen/Qwen3-14B /mnt/external/checkpoints/Qwen/Qwen3-14B/nemotron_code_char16k_cakld_ctx4096_self_clip/ /mnt/external/data/nemotron/nemotron-sft-code-char16k_526k.jsonl /mnt/external/checkpoints/Qwen/Qwen3-14B/nemotron_code_char16k_cakld_ctx4096_self_clip/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-14B/int2-g64-code_nemotron.pt 4096
    # - ./train.sh Qwen/Qwen3-14B /mnt/external/checkpoints/Qwen/Qwen3-14B/OpenR1-Math-220k_default_cakld_ctx4096_self_clip/ /mnt/external/data/OpenR1-Math-220k/default.json /mnt/external/checkpoints/Qwen/Qwen3-14B/OpenR1-Math-220k_default_cakld_ctx4096_self_clip/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-14B/int2-g64-openr1_math.pt 4096

    ### Checkpoint-0
    # - ./train_ckpt0.sh Qwen/Qwen3-14B /mnt/external/checkpoints/Qwen/Qwen3-14B/checkpoint_0/ /mnt/external/data/OpenR1-Math-220k/default.json /mnt/external/checkpoints/Qwen/Qwen3-14B/checkpoint_0/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-14B/int2-g64.pt 4096

    ### No-clip training
    # - ./train_noclip.sh Qwen/Qwen3-8B /mnt/external/checkpoints/Qwen/Qwen3-8B/1b-grad-l3-r0.5_cakld_noclip_ctx4096/ /mnt/external/data/data_efficacy/processed_1b-grad-l3-r0.5.jsonl /mnt/external/checkpoints/Qwen/Qwen3-8B/1b-grad-l3-r0.5_cakld_noclip_ctx4096/logs/ 4096
    # - ./train_noclip.sh Qwen/Qwen3-8B /mnt/external/checkpoints/Qwen/Qwen3-8B/1b-random-r0.5_cakld_noclip_ctx4096/ /mnt/external/data/data_efficacy/processed_1b-random-r0.5.jsonl /mnt/external/checkpoints/Qwen/Qwen3-8B/1b-random-r0.5_cakld_noclip_ctx4096/logs/ 4096
    # - ./train_noclip.sh Qwen/Qwen3-14B /mnt/external/checkpoints/Qwen/Qwen3-14B/1b-grad-l3-r0.5_cakld_noclip_ctx4096/ /mnt/external/data/data_efficacy/processed_1b-grad-l3-r0.5.jsonl /mnt/external/checkpoints/Qwen/Qwen3-14B/1b-grad-l3-r0.5_cakld_noclip_ctx4096/logs/ 4096
    # - ./train_noclip.sh Qwen/Qwen3-14B /mnt/external/checkpoints/Qwen/Qwen3-14B/1b-random-r0.5_cakld_noclip_ctx4096/ /mnt/external/data/data_efficacy/processed_1b-random-r0.5.jsonl /mnt/external/checkpoints/Qwen/Qwen3-14B/1b-random-r0.5_cakld_noclip_ctx4096/logs/ 4096

    ### V1.0 summary
    # - ./train_cosine_zero3.sh Qwen/Qwen3-14B /mnt/external/checkpoints/Qwen/Qwen3-14B/nemotron_code_cakld_ctx32768/ /mnt/external/data/nemotron/code/nemotron-sft-code_500K_block_0.jsonl /mnt/external/checkpoints/Qwen/Qwen3-14B/nemotron_code_cakld_ctx32768/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-14B/int2-g64-code_nemotron.pt 32768
    - ./train_cosine.sh Qwen/Qwen3-14B /mnt/external/checkpoints/Qwen/Qwen3-14B/nemotron_code_cakld_ctx16384/ /mnt/external/data/nemotron/code/nemotron-sft-code_500K_block_0_repeat4.jsonl /mnt/external/checkpoints/Qwen/Qwen3-14B/nemotron_code_cakld_ctx16384/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-14B/int2-g64-code_nemotron.pt 16384


    # - cd /mnt/external
    # - nohup python keep.py --gpus=4 --interval=0.2 >/dev/null 2>&1 &
    # - sleep 100000000
  tags: ["Debug:True"]
  priority: High
  azml_int: True
