description: Simple Amulet job on Singularity

target:
  service: sing
  name: msrresrchbasicvc
  workspace_name: dca-singularity

environment:
  image: amlt-sing/acpt-torch2.5.0-py3.10-cuda12.4-ubuntu22.04
  setup:
    - pwd
    - sudo apt-get update
    - sudo apt-get install -y vim
    - pip install uv
    - uv venv venv_openr1 --python 3.11
    - source venv_openr1/bin/activate
    - uv pip install --upgrade pip setuptools packaging wheel ninja

    - uv pip install vllm==0.7.2
    - cd /scratch/amlt_code/test/3rdparty/open-r1
    - GIT_LFS_SKIP_SMUDGE=1 uv pip install -e ".[dev]"
    - uv pip install transformers==4.51.3
    - uv pip install flash-attn==2.7.4.post1 --no-build-isolation

    - echo -e "alias ll='ls -al'" >> ~/.bashrc

storage:
  input:
    storage_account_name: dcasingularity4556773921
    container_name: qingtaoli
    mount_dir: /mnt/input
  output:
    storage_account_name: dcasingularity4556773921
    container_name: qingtaoli
    mount_dir: /mnt/output
  external:
    storage_account_name: dcasingularity4556773921
    container_name: qingtaoli
    mount_dir: /mnt/external

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: ./

data:
  storage_id: external


jobs:
- name: bd_test_qwen3_14b_grad_cakld_1600_math500
  sku: NC_A100_v4:G4
  identity: managed
  submit_args:
    env:
      _AZUREML_SINGULARITY_JOB_UAI: "/subscriptions/656a79af-6a27-4924-ad92-9221860e3bba/resourceGroups/dca-core/providers/Microsoft.ManagedIdentity/userAssignedIdentities/dca-core-identity"
  command:
    - source venv_openr1/bin/activate
    - huggingface-cli login --token <hf_token>

    - cd /scratch/amlt_code/scripts/code_modify
    - chmod +x ./modify*.sh
    - ./modify_for_openr1_test_gpqa.sh

    - cd /scratch/amlt_code/test/3rdparty/open-r1
    - export NUM_GPUS=4

    - export MODEL_DIR=/mnt/external/checkpoints/Qwen/Qwen3-14B/1b-grad-l3-r0.5_cakld_ctx4096/checkpoint-1600/
    - export MODEL_ARGS="pretrained=$$MODEL_DIR,dtype=bfloat16,data_parallel_size=$$NUM_GPUS,max_model_length=32768,gpu_memory_utilization=0.9,generation_parameters={max_new_tokens:32768,temperature:0.6,top_p:0.95},bits=2,group_size=64,quant_type=int"
    - export OUTPUT_DIR=$$MODEL_DIR/evals
    - lighteval vllm $$MODEL_ARGS "custom|math_500|0|0" --custom-tasks src/open_r1/evaluate.py --use-chat-template --output-dir $$OUTPUT_DIR --save-details



    ### Command Backup ###
    # - cd /scratch/amlt_code/scripts/code_modify
    # - chmod +x ./modify*.sh
    # - ./modify_for_openr1_test_gpqa.sh
    # - ./modify_for_openr1_test_aime.sh

    # - cd /scratch/amlt_code/test/3rdparty/open-r1
    # - export NUM_GPUS=4

    # - export MODEL_DIR=/mnt/external/checkpoints/Qwen/Qwen3-8B/1b-grad-l3-r0.5_cakld_ctx4096/checkpoint-400/
    # - export MODEL_ARGS="pretrained=$$MODEL_DIR,dtype=bfloat16,data_parallel_size=$$NUM_GPUS,max_model_length=32768,gpu_memory_utilization=0.9,generation_parameters={max_new_tokens:32768,temperature:0.6,top_p:0.95},bits=2,group_size=64,quant_type=int"
    # - export OUTPUT_DIR=$$MODEL_DIR/evals
    # - lighteval vllm $$MODEL_ARGS "custom|aime24|0|0" --custom-tasks src/open_r1/evaluate.py --use-chat-template --output-dir $$OUTPUT_DIR --save-details
    # - lighteval vllm $$MODEL_ARGS "custom|math_500|0|0" --custom-tasks src/open_r1/evaluate.py --use-chat-template --output-dir $$OUTPUT_DIR --save-details
    # - lighteval vllm $$MODEL_ARGS "custom|gpqa:diamond|0|0" --custom-tasks src/open_r1/evaluate.py --use-chat-template --output-dir $$OUTPUT_DIR --save-details

  tags: ["Debug:True"]
  priority: High
  azml_int: True

- name: bd_test_qwen3_14b_grad_cakld_16800_gpqa
  sku: NC_A100_v4:G4
  identity: managed
  submit_args:
    env:
      _AZUREML_SINGULARITY_JOB_UAI: "/subscriptions/656a79af-6a27-4924-ad92-9221860e3bba/resourceGroups/dca-core/providers/Microsoft.ManagedIdentity/userAssignedIdentities/dca-core-identity"
  command:
    - source venv_openr1/bin/activate
    - huggingface-cli login --token <hf_token>

    - cd /scratch/amlt_code/scripts/code_modify
    - chmod +x ./modify*.sh
    - ./modify_for_openr1_test_gpqa.sh

    - cd /scratch/amlt_code/test/3rdparty/open-r1
    - export NUM_GPUS=4

    - export MODEL_DIR=/mnt/external/checkpoints/Qwen/Qwen3-14B/1b-grad-l3-r0.5_cakld_ctx4096/checkpoint-1600/
    - export MODEL_ARGS="pretrained=$$MODEL_DIR,dtype=bfloat16,data_parallel_size=$$NUM_GPUS,max_model_length=32768,gpu_memory_utilization=0.9,generation_parameters={max_new_tokens:32768,temperature:0.6,top_p:0.95},bits=2,group_size=64,quant_type=int"
    - export OUTPUT_DIR=$$MODEL_DIR/evals
    - lighteval vllm $$MODEL_ARGS "custom|gpqa:diamond|0|0" --custom-tasks src/open_r1/evaluate.py --use-chat-template --output-dir $$OUTPUT_DIR --save-details

  tags: ["Debug:True"]
  priority: High
  azml_int: True

- name: bd_test_qwen3_14b_grad_cakld_1600_aime
  sku: NC_A100_v4:G4
  identity: managed
  submit_args:
    env:
      _AZUREML_SINGULARITY_JOB_UAI: "/subscriptions/656a79af-6a27-4924-ad92-9221860e3bba/resourceGroups/dca-core/providers/Microsoft.ManagedIdentity/userAssignedIdentities/dca-core-identity"
  command:
    - source venv_openr1/bin/activate
    - huggingface-cli login --token <hf_token>

    - cd /scratch/amlt_code/scripts/code_modify
    - chmod +x ./modify*.sh
    - ./modify_for_openr1_test_aime.sh

    - cd /scratch/amlt_code/test/3rdparty/open-r1
    - export NUM_GPUS=4

    - export MODEL_DIR=/mnt/external/checkpoints/Qwen/Qwen3-14B/1b-grad-l3-r0.5_cakld_ctx4096/checkpoint-1600/
    - export MODEL_ARGS="pretrained=$$MODEL_DIR,dtype=bfloat16,data_parallel_size=$$NUM_GPUS,max_model_length=32768,gpu_memory_utilization=0.9,generation_parameters={max_new_tokens:32768,temperature:0.6,top_p:0.95},bits=2,group_size=64,quant_type=int"
    - export OUTPUT_DIR=$$MODEL_DIR/evals
    - lighteval vllm $$MODEL_ARGS "custom|aime24|0|0" --custom-tasks src/open_r1/evaluate.py --use-chat-template --output-dir $$OUTPUT_DIR --save-details

  tags: ["Debug:True"]
  priority: High
  azml_int: True

