description: Simple Amulet job on Singularity

target:
  service: sing
  name: whitney08
  workspace_name: dca-singularity

environment:
  image: amlt-sing/acpt-rocm6.1_ubuntu20.04_py3.9_pytorch2.1.2
  setup:
    - pwd
    - sudo apt-get update
    - sudo apt-get install -y vim
    - pip install uv
    - uv venv venv_bd --python 3.11
    - source venv_bd/bin/activate
    - ls -l
    - uv pip install --upgrade pip setuptools packaging wheel ninja

    # bitsandbytes HIP bug
    # - line=major, minor = map(int, torch.version.cuda.split("."))
    # - pip install --force-reinstall 'https://github.com/bitsandbytes-foundation/bitsandbytes/releases/download/continuous-release_multi-backend-refactor/bitsandbytes-0.45.3.dev272-py3-none-manylinux_2_24_x86_64.whl'
    
    - uv pip install torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 --index-url https://download.pytorch.org/whl/rocm6.1
    - cd /scratch/amlt_code
    - uv pip install -r ./requirement_20250507_transformers_4.51.3.txt
    - uv pip install flash-attn==2.7.4.post1 --no-build-isolation

    - echo -e "alias ll='ls -al'" >> ~/.bashrc

    - cd /scratch/amlt_code/scripts/code_modify
    - chmod +x ./modify*.sh
    - ./modify_for_bd_train.sh

storage:
  input:
    storage_account_name: dcasingularity4556773921
    container_name: qingtaoli
    mount_dir: /mnt/input
  output:
    storage_account_name: dcasingularity4556773921
    container_name: qingtaoli
    mount_dir: /mnt/output
  external:
    storage_account_name: dcasingularity4556773921
    container_name: qingtaoli
    mount_dir: /mnt/external

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: ./

data:
  storage_id: external


jobs:
- name: bd_qwen3_MI300
  sku: NDMI300Xv5:G4
  identity: managed
  submit_args:
    env:
      _AZUREML_SINGULARITY_JOB_UAI: "/subscriptions/656a79af-6a27-4924-ad92-9221860e3bba/resourceGroups/dca-core/providers/Microsoft.ManagedIdentity/userAssignedIdentities/dca-core-identity"
  command:
    - cd scripts/train
    - chmod +x ./train*.sh
    - export NCCL_DEBUG=WARN
    # - ./train_8gpu_14b.sh /mnt/external/models/deepseek-ai/DeepSeek-R1-Distill-Qwen-14B/ /mnt/external/checkpoints/DeepSeek-R1-Distill-Qwen-14B_teacher_gen/20250513_openr1_math220k_default_ctx32k/ /mnt/external/data/teacher_gen/Qwen-14B/default.json /mnt/external/checkpoints/DeepSeek-R1-Distill-Qwen-14B_teacher_gen/20250513_openr1_math220k_default_ctx32k/logs/ /mnt/external/data/clip_cache/deepseek-ai/DeepSeek-R1-Distill-Qwen-14B/int2-g64.pt 32768
    # - ./train.sh /mnt/external/models/microsoft/Phi-4-reasoning/ /mnt/external/checkpoints/microsoft/Phi-4-reasoning/20250525_alpaca5kwiki3k_ctx4096/ /mnt/external/data/generation/microsoft/Phi-4-reasoning-ctx4096/wiki-alpaca/mix_alpaca_wikitext_8000.json /mnt/external/checkpoints/microsoft/Phi-4-reasoning/20250525_alpaca5kwiki3k_ctx4096/logs/ /mnt/external/data/clip_cache/microsoft/Phi-4-reasoning/int2-g64.pt 4096
    # - ./train.sh Qwen/Qwen3-8B /mnt/external/checkpoints/Qwen/Qwen3-8B/1b-grad-l3-r0.5_cakld_ctx4096/ /mnt/external/data/data_efficacy/processed_1b-grad-l3-r0.5.jsonl /mnt/external/checkpoints/Qwen/Qwen3-8B/1b-grad-l3-r0.5_cakld_ctx4096/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-8B/int2-g64.pt 4096
    # - ./train.sh Qwen/Qwen3-8B /mnt/external/checkpoints/Qwen/Qwen3-8B/1b-random-r0.5_nokd_ctx4096/ /mnt/external/data/data_efficacy/processed_1b-random-r0.5.jsonl /mnt/external/checkpoints/Qwen/Qwen3-8B/1b-random-r0.5_nokd_ctx4096/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-8B/int2-g64.pt 4096
    - ./train.sh Qwen/Qwen3-8B /mnt/external/checkpoints/Qwen/Qwen3-8B/1b-grad-l3-r0.5_nokd_ctx4096/ /mnt/external/data/data_efficacy/processed_1b-grad-l3-r0.5.jsonl /mnt/external/checkpoints/Qwen/Qwen3-8B/1b-grad-l3-r0.5_nokd_ctx4096/logs/ /mnt/external/data/clip_cache/Qwen/Qwen3-8B/int2-g64.pt 4096
  tags: ["Debug:True"]
  priority: High
  azml_int: True
